---
# gce_instance_name
# gce_machine_type
# gce_zone
# gce_tags
# disks

- name: gce / disk / boot
  gce_pd:
    zone: "{{ gce_zone }}"
    name: "{{ gce_instance_name }}-disk-{{ item.id }}"
    size_gb: "{{ item.size_gb }}"
    image: "{{ item.gce_image }}"
    mode: READ_WRITE
  with_items: "{{ disks }}"
  when: item.id == 0

- name: gce / launch
  gce:
    instance_names: "{{ gce_instance_name }}"
    zone: "{{ gce_zone }}"
    machine_type: "{{ gce_machine_type }}"
    state: present
    tags: "{{ gce_tags }}"
    disks:
      - name: "{{ gce_instance_name }}-disk-0"
        mode: READ_WRITE
  register: gce

- name: gce / disks / data
  gce_pd:
    instance_name: "{{ gce_instance_name }}"
    zone: "{{ gce_zone }}"
    name: "{{ gce_instance_name }}-disk-{{ item.id }}"
    size_gb: "{{ item.size_gb }}"
    mode: READ_WRITE
  with_items: "{{ disks }}"
  when: item.id > 0

- name: work instances
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: work_instances
  with_items: "{{ gce.instance_data }}"

- name: gce / ssh / ready
  wait_for:
    delay: 1
    host: "{{ item.public_ip }}"
    port: 22
    state: started
    timeout: 120
  with_items: "{{ gce.instance_data }}"

- set_fact:
    work_hosts: {
      name: "{{ item.name }}",
      ip: "{{ item.public_ip }}"
    }
  with_items: "{{ gce.instance_data }}"

- debug:
    var: work_hosts
