---
- debug:
    var: docker_version
- debug:
    var: docker_compose_version

- name: install docker
  shell: apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D &&
         echo deb http://apt.dockerproject.org/repo debian-jessie main > /etc/apt/sources.list.d/docker.list &&
         apt-get update &&
         apt-get install -y docker-engine={{ docker_version }}~debian-jessie &&
         service docker start

- name: install docker-compose
  shell: curl -L https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/run.sh > /usr/local/bin/docker-compose &&
         chmod +x /usr/local/bin/docker-compose
