---
- debug: var=db_user
- debug: var=db_password
- debug: var=db_name
- debug: var=filename

- name: mysql / dump database
  shell: mysqldump -u {{ db_user }} -p{{ db_password }} {{ db_name }} |
         gzip > {{ filename }}
