---
- debug: var=app
- debug: var=user
- debug: var=dir_opt

- set_fact:
    dir_app: "/opt/{{ app }}"

- name: group
  group:
    name: "{{ user }}"
    state: present

- name: user
  user:
    name: "{{ user }}"
    group: "{{ user }}"
    shell: /bin/bash
    state: present

- name: app directory
  file:
    path: "{{ dir_app }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

# app/bin|etc|user_ssh|log
- name: app opt
  copy:
    src: "{{ dir_opt }}/"
    dest: "{{ dir_app }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600

- name: app log
  file:
    path: "{{ dir_app }}/log"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

- name: chmod app
  file:
    path: "{{ dir_app }}"
    state: directory
    mode: u+rwX,go-rwx
    recurse: true

- name: chmod app/bin
  file:
    path: "{{ dir_app }}/bin"
    state: directory
    mode: u+rwx,go-rwx
    recurse: true

- name: link ~user/.ssh to /opt/app/user_ssh
  file:
    src: "{{ dir_app }}/user_ssh"
    dest: "~{{ user }}/.ssh"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
