---
- debug: var=app
- debug: var=user
- debug: var=dir_opt

- set_fact:
    dir_app: "/opt/{{ app }}"

- name: group
  group:
    name: "{{ user }}"
    state: present

- name: user
  user:
    name: "{{ user }}"
    group: "{{ user }}"
    shell: /bin/bash
    state: present

- name: /opt/app/
  file:
    path: "{{ dir_app }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

- name: /opt/app/[bin|etc|user_ssh|log]/
  copy:
    src: "{{ dir_opt }}/"
    dest: "{{ dir_app }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600

- name: /opt/app/[dir]/ pre-created
  file:
    path: "{{ dir_app }}/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700
  with_items:
    - log

- name: link ~user/.ssh to /opt/app/user_ssh
  file:
    src: "{{ dir_app }}/user_ssh"
    dest: "~{{ user }}/.ssh"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link

- include: chmod.yml
