---
- debug: var=app
- debug: var=user
- debug: var=etc

- name: dir_app
  command: "echo /opt/{{ app }}"
  register: dir_app

- name: dir_app_etc
  command: "echo {{ dir_app.stdout }}/etc"
  register: dir_app_etc

- name: dir_app_log
  command: "echo {{ dir_app.stdout }}/log"
  register: dir_app_log

- name: group
  group:
    name: "{{ user }}"
    state: present

- name: user
  user:
    name: "{{ user }}"
    group: "{{ user }}"
    shell: /bin/bash
    state: present

- name: app directory
  file:
    path: "{{ dir_app.stdout }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

# etc/user_ssh - linked from ~user/.ssh for capistrano
# etc/[others] - capistrano-stage-specific configs
- name: app etc
  copy:
    src: "{{ etc }}"
    dest: "{{ dir_app.stdout }}/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600

- name: app log
  file:
    path: "{{ dir_app_log.stdout }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

- name: app directory / chmod
  file:
    path: "{{ dir_app.stdout }}"
    state: directory
    mode: u+rwX,go-rwx
    recurse: true

- name: link ~user/.ssh to /opt/app/etc/user_ssh
  file:
    src: "{{ dir_app_etc.stdout }}/user_ssh"
    dest: "~{{ user }}/.ssh"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
