---
- debug: var=docker_compose_version

- name: docker / setup
  become: true
  shell: apt-get update &&
          apt-get upgrade -y &&
          apt-get install -y --no-install-recommends
            git &&
          apt-get install -y --no-install-recommends
            apt-transport-https
            ca-certificates
            curl
            gnupg2
            software-properties-common &&
          curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - &&
          echo deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable > /etc/apt/sources.list.d/docker.list &&
          apt-get update &&
          apt-get install -y --no-install-recommends
            docker-ce &&
          curl -L https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose &&
          chmod +x /usr/local/bin/docker-compose