---
- debug: var=backup_dest
- debug: var=backup_username
- debug: var=backup_password

# couchbase-cli user-manage -c [host]:8091 -u [admin] -p [password] [options]
- name: couchbase / user / manage
  command: >
    /opt/couchbase/bin/couchbase-cli user-manage -c localhost:8091 \
    -u {{ username }} \
    -p {{ password }} \
    --set \
    --ro-username={{ backup_username }} \
    --ro-password={{ backup_password }}

- template:
    src: ../templates/opt/bin/backup-couchbase.sh
    dest: /opt/bin/backup-couchbase.sh
    owner: root
    group: root
    mode: 0755
