---

# couchbase-cli bucket-create -c [host]:8091 -u [admin] -p [password] [options]
- name: couchbase / bucket / create
  command: >
    /opt/couchbase/bin/couchbase-cli bucket-create -c localhost:8091 \
    -u {{ username }} \
    -p {{ password }} \
    --bucket={{ bucket.name }} \
    --bucket-ramsize={{ bucket.ramsize }} \
    --bucket-type={{ bucket.type }} \
    --bucket-replica=1 \
    --enable-index-replica=1 \
    --enable-flush=0
  when: couchbase_not_installed
