---

# couchbase-cli cluster-init --c [host]:8091 [options]
- name: couchbase / cluster / init
  command: >
    /opt/couchbase/bin/couchbase-cli cluster-init \
    --cluster localhost:8091 \
    --cluster-username={{ username }} \
    --cluster-password={{ password }} \
    --cluster-port=8091 \
    --cluster-ramsize={{ cluster_ramsize }} \
    --cluster-name={{ cluster_name }} \
    --cluster-index-ramsize={{ index_ramsize }} \
    --cluster-fts-ramsize={{ fts_ramsize }} \
    --index-storage-setting=default \
    --services=data,index,query,fts
  when: couchbase_not_installed
