---

- name: check
  command: dpkg-query -W couchbase-server-community
  register: couchbase_deb
  failed_when: couchbase_deb.rc > 1 # don't fail
  changed_when: couchbase_deb.rc == 1 # not found

- set_fact:
    couchbase_not_installed: "{{ couchbase_deb.rc == 1 }}"

# https://packages.couchbase.com/releases/4.5.1/couchbase-server-community_4.5.1-debian8_amd64.deb"
# https://packages.couchbase.com/releases/4.5.1/couchbase-server-community-dbg_4.5.1-debian8_amd64.deb
- name: download
  get_url:
    url="https://packages.couchbase.com/releases/{{ couchbase_version }}/couchbase-server-community_{{ couchbase_version }}-{{ debian_version }}.deb"
    dest="/tmp/couchbase-server-community_{{ couchbase_version }}-{{ debian_version }}.deb"
  when: couchbase_not_installed

- name: install
  apt: deb=/tmp/couchbase-server-community_{{ couchbase_version }}-{{ debian_version }}.deb
  when: couchbase_not_installed

- name: dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: couchbase
    group: couchbase
  with_items:
    - "{{ node_data_path }}"
    - "{{ node_index_path }}"

- include_role:
    name: couchbase
    tasks_from: node_init
