---

- name: gce
  hosts: localhost
  gather_facts: no
  roles:
    - {
        role: gce
      }

- name: host / data disk
  hosts: work_instances
  gather_facts: no
  become: true
  tasks:

    - include_role:
        name: base
        tasks_from: disk_format
      vars:
        device: "{{ item.device }}"
        fstype: "{{ item.fstype }}"
        path: "{{ item.path }}"
      with_items: "{{ disks }}"
      when: item.id > 0

    - include_role:
        name: base
        tasks_from: folder_link
      vars:
        mode: "{{ item.mode }}"
        folder: "{{ item.folder }}"
        link: "{{ item.link }}"
      with_items: "{{ folder_links }}"
