---
- debug: var=user

- name: docker / user
  user:
    name: "{{ user }}"
    groups: docker
    state: present

- include: network.yml network="{{ item }}"
  with_items: "{{ docker_networks }}"

- include: volume.yml volume="{{ item }}"
  with_items: "{{ docker_volumes }}"
